language: rust
rust:
  - 1.15.0
  - 1.22.0
  - 1.26.0
  - stable
  - beta
  - nightly
matrix:
  include:
    # try a target that doesn't have std at all
    - rust: stable
      env: TARGET=thumbv6m-none-eabi
      script:
        - rustup target add $TARGET
        - cargo build --verbose --target $TARGET --no-default-features
sudo: false
script:
  - cargo build --verbose
  - ./ci/test_full.sh
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
