bridges = []
persistence_dir = './conductor-config.toml'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = './key.key'
name = 'testAgent'
public_address = 'HcSciGpYDHTaa5dmw583AO7Jy9kHz9K3gu6MtTsB8Nwbfe3y3hD8rOb9aj5B8za'

[[dnas]]
file = './dist/dna-src.dna.json'
hash = 'QmXye7ojb4Vivj2EvxhJSvnHQUKMjgf9UAdQhxVoVSRQXB'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'acorn'

[instances.storage]
type = 'pickle'
path = './storage'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'acorn'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = false
type = 'info'
[[logger.rules.rules]]
exclude = true
pattern = '.*'

[[logger.rules.rules]]
exclude = false
pattern = '^lib3h'

[[logger.rules.rules]]
exclude = false
pattern = '^sim2h'

[[logger.rules.rules]]
exclude = false
pattern = '^holochain'

[[logger.rules.rules]]
exclude = true
pattern = '^holochain_core_types'

[network]
sim2h_url = 'wss://0.0.0.0:9000/'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
