bridges = []
persistence_dir = '.'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'development-agent'
keystore_file = 'unused'
name = 'acorn user'
public_address = 'HcScIc8G7X769Nr6cnRxgR73wi8au946z7hc46EMDJjaz8au4bD7V6hj7T6B8fa'
test_agent = true

[[dnas]]
file = './dnas/profiles/dist/profiles.dna.json'
hash = 'QmeAyJ8Zw335GH8DGDCNkHRGyeKTv2cddUPkFQNuzHjhD4'
id = 'profiles-dna'

[[dnas]]
file = './dna/QmZMPCoaitDzF498VjGHDuGz5vq41g1xFMq6KqFgdKoFna.dna.json'
hash = 'QmZMPCoaitDzF498VjGHDuGz5vq41g1xFMq6KqFgdKoFna'
id = '_acorn_projects_dna_0.39446223089992405'
uuid = 'uuid-atrium-dealmaker-chivalry-amniotic-spokesman'

[[instances]]
agent = 'development-agent'
dna = 'profiles-dna'
id = 'profiles-instance'

[instances.storage]
type = 'memory'

[[instances]]
agent = 'development-agent'
dna = '_acorn_projects_dna_0.39446223089992405'
id = '_acorn_projects_instance_0.39446223089992405'

[instances.storage]
path = './storage/_acorn_projects_instance_0.39446223089992405'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'profiles-instance'

[[interfaces.instances]]
id = '_acorn_projects_instance_0.39446223089992405'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = false
type = 'info'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
