bridges = []
persistence_dir = '.'

[[agents]]
id = 'acorn-profiles-instance-agent'
keystore_file = 'unused'
name = 'acorn user'
public_address = 'HcScIc8G7X769Nr6cnRxgR73wi8au946z7hc46EMDJjaz8au4bD7V6hj7T6B8fa'
test_agent = true

[[dnas]]
file = './dnas/profiles/dist/profiles.dna.json'
hash = 'QmTT6oSPHNFn4x9ssBM14M1HznLVGjrFKCyBcsTyBudzfg'
id = 'acorn-profiles-dna'

[[instances]]
agent = 'acorn-profiles-instance-agent'
dna = 'acorn-profiles-dna'
id = 'acorn-profiles-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'Acorn-interface'

[[interfaces.instances]]
id = 'acorn-profiles-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[[ui_bundles]]
hash = 'QmTT6oSPHNFn4x9ssBM14M1HznLVGjrFKCyBcsTyBudzfg'
id = 'dna-connections'
root_dir = './irrelevant'

[[ui_interfaces]]
bind_address = '127.0.0.1'
bundle = 'dna-connections'
dna_interface = 'Acorn-interface'
id = 'dna-connections-interface'
port = 3111
reroute_to_root = true

[logger]
state_dump = false
type = 'info'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
